version: "3.7"

services:
  db:
    image: 'mysql:5.7'
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: ujusy
      MYSQL_ROOT_PASSWORD: 1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci